name: Headless Navegador - Enviar Data

on:
  schedule:
    - cron: '*/2 * * * *'  # Executa automaticamente a cada 2 minutos (UTC)
  workflow_dispatch:       # Também permite execução manual

jobs:
  enviar_data_php:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Playwright com dependências
        run: |
          npm install -D playwright
          npx playwright install --with-deps

      - name: Executar script headless
        run: node bot.js
